# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ray Krow's Blog | A blog about web programming languages and creative software solutions
email: raymondkrow@gmail.com
description: > # "baseurl:"
  I'm Ray Krow, a tech obsessed software engineer, and this is my
  slice of the internet I've cut out for a personal blog. You can
  find information on frameworks and tooling for C# and .NET,
  Javascript, CSS, Python and Flask, and most anything else
  web related.
baseurl: "" # the subpath of your site, e.g. /blog
source_url: "https://github.com/raykrow/raykrow.github.io"
url: "http://krow.tech" # the base hostname & protocol for your site
github_username: raykrow

meta_description: >
  I'm Ray Krow and this is my blog where I talk about web development
  programming languages like C#, Python, Ruby, Javascript and
  their most popular frameworks and libraries like angular, automapper,
  .Net, Flask, Jkeyll and more.

# Build settings
markdown: kramdown
repository: raykrow/raykrow.github.io
permalink: '/posts/:title'
<<<<<<< HEAD
gems:
  - jekyll-seo-tag
=======
sass:
  sass_dir: _sass
  style: compressed
>>>>>>> master
